# Generated by Django 2.1 on 2019-10-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
